pipeline {
    agent { docker { image 'python:3.10.1-alpine' } }

    stages {
        stage('version') {
            steps {
                sh 'python --version'
            }
        }
        stage('unit') {
            steps {
                sh 'python -m pytest tests'
            }
        }
    }
}
