pipeline {
    agent { docker { image 'python:3.10.1-alpine' } }

    stages {
        stage('version') {
            steps {
                sh 'python --version'
            }
        }
        stage('build') {
            steps {
                sh 'id'
                sh 'pwd'
                sh 'ls -al'
                sh 'ls -al /var/jenkins_home/workspace/mymath@tmp'
                sh 'python -m pip install --user pytest'
            }
        }
        stage('unit tests') {
            steps {
                sh 'python -m pytest tests'
            }
        }
    }
}
